name = "RedBlueSegInt0"
uuid = "503f59ad-57cd-4c28-b835-7653701bf0ed"
version = "0.1.0"
authors = ["Jack Snoeyink <snoeyink@cs.unc.edu>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
BenchmarkTools = "1.8.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
